
CREATE TABLE IF NOT EXISTS `ph_city_town` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `city_town` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `province_iso` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=122 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `ph_city_town` (`id`, `city_town`, `province_iso`) VALUES
(1, 'Bangued', 'PH-ABR'),
(2, 'Boliney', 'PH-ABR'),
(3, 'Bucay', 'PH-ABR'),
(4, 'Bucloc', 'PH-ABR'),
(5, 'Daguioman', 'PH-ABR'),
(6, 'Danglas', 'PH-ABR'),
(7, 'Dolores', 'PH-ABR'),
(8, 'La Paz', 'PH-ABR'),
(9, 'Lacub', 'PH-ABR'),
(10, 'Lagangilang', 'PH-ABR'),
(11, 'Lagayan', 'PH-ABR'),
(12, 'Langiden', 'PH-ABR'),
(13, 'Licuan-Baay (Licuan)', 'PH-ABR'),
(14, 'Luba', 'PH-ABR'),
(15, 'Malibcong', 'PH-ABR'),
(16, 'Manabo', 'PH-ABR'),
(17, 'Peñarrubia', 'PH-ABR'),
(18, 'Pidigan', 'PH-ABR'),
(19, 'Pilar', 'PH-ABR'),
(20, 'Sallapadan', 'PH-ABR'),
(21, 'San Isidro', 'PH-ABR'),
(22, 'San Juan', 'PH-ABR'),
(23, 'San Quintin', 'PH-ABR'),
(24, 'Tayum', 'PH-ABR'),
(25, 'Tineg', 'PH-ABR'),
(26, 'Tubo', 'PH-ABR'),
(27, 'Villaviciosa', 'PH-ABR'),
(28, 'Buenavista', 'PH-AGN'),
(29, 'Butuan', 'PH-AGN'),
(30, 'Cabadbaran', 'PH-AGN'),
(31, 'Carmen', 'PH-AGN'),
(32, 'Jabonga', 'PH-AGN'),
(33, 'Kitcharao', 'PH-AGN'),
(34, 'Las Nieves', 'PH-AGN'),
(35, 'Magallanes', 'PH-AGN'),
(36, 'Nasipit', 'PH-AGN'),
(37, 'Remedios T. Romualdez', 'PH-AGN'),
(38, 'Santiago', 'PH-AGN'),
(39, 'Tubay', 'PH-AGN'),
(40, 'Bayugan', 'PH-AGS'),
(41, 'Bunawan', 'PH-AGS'),
(42, 'Esperanza', 'PH-AGS'),
(43, 'La Paz', 'PH-AGS'),
(44, 'Loreto', 'PH-AGS'),
(45, 'Prosperidad', 'PH-AGS'),
(46, 'Rosario', 'PH-AGS'),
(47, 'San Francisco', 'PH-AGS'),
(48, 'San Luis', 'PH-AGS'),
(49, 'Santa Josefa', 'PH-AGS'),
(50, 'Sibagat', 'PH-AGS'),
(51, 'Talacogon', 'PH-AGS'),
(52, 'Trento', 'PH-AGS'),
(53, 'Veruela', 'PH-AGS'),
(54, 'Altavas', 'PH-AKL'),
(55, 'Balete', 'PH-AKL'),
(56, 'Banga', 'PH-AKL'),
(57, 'Batan', 'PH-AKL'),
(58, 'Buruanga', 'PH-AKL'),
(59, 'Ibajay', 'PH-AKL'),
(60, 'Kalibo', 'PH-AKL'),
(61, 'Lezo', 'PH-AKL'),
(62, 'Libacao', 'PH-AKL'),
(63, 'Madalag', 'PH-AKL'),
(64, 'Makato', 'PH-AKL'),
(65, 'Malay', 'PH-AKL'),
(66, 'Malinao', 'PH-AKL'),
(67, 'Nabas', 'PH-AKL'),
(68, 'New Washington', 'PH-AKL'),
(69, 'Numancia', 'PH-AKL'),
(70, 'Tangalan', 'PH-AKL'),
(71, 'Bacacay', 'PH-ALB'),
(72, 'Camalig', 'PH-ALB'),
(73, 'Daraga (Locsin)', 'PH-ALB'),
(74, 'Guinobatan', 'PH-ALB'),
(75, 'Jovellar', 'PH-ALB'),
(76, 'Legazpi', 'PH-ALB'),
(77, 'Libon', 'PH-ALB'),
(78, 'Ligao', 'PH-ALB'),
(79, 'Malilipot', 'PH-ALB'),
(80, 'Malinao', 'PH-ALB'),
(81, 'Manito', 'PH-ALB'),
(82, 'Oas', 'PH-ALB'),
(83, 'Pio Duran', 'PH-ALB'),
(84, 'Polangui', 'PH-ALB'),
(85, 'Rapu-Rapu', 'PH-ALB'),
(86, 'Santo Domingo (Libog)', 'PH-ALB'),
(87, 'Tabaco', 'PH-ALB'),
(88, 'Tiwi', 'PH-ALB'),
(89, 'Anini-y', 'PH-ANT'),
(90, 'Barbaza', 'PH-ANT'),
(91, 'Belison', 'PH-ANT'),
(92, 'Bugasong', 'PH-ANT'),
(93, 'Caluya', 'PH-ANT'),
(94, 'Culasi', 'PH-ANT'),
(95, 'Hamtic', 'PH-ANT'),
(96, 'Laua-an', 'PH-ANT'),
(97, 'Libertad', 'PH-ANT'),
(98, 'Pandan', 'PH-ANT'),
(99, 'Patnongon', 'PH-ANT'),
(100, 'San Jose de Buenavista', 'PH-ANT'),
(101, 'San Remigio', 'PH-ANT'),
(102, 'Sebaste', 'PH-ANT'),
(103, 'Sibalom', 'PH-ANT'),
(104, 'Tibiao', 'PH-ANT'),
(105, 'Tobias Fornier', 'PH-ANT'),
(106, 'Valderrama', 'PH-ANT'),
(107, 'Calanasan', 'PH-APA'),
(108, 'Conner', 'PH-APA'),
(109, 'Flora', 'PH-APA'),
(110, 'Kabugao', 'PH-APA'),
(111, 'Luna', 'PH-APA'),
(112, 'Pudtol', 'PH-APA'),
(113, 'Santa Marcela', 'PH-APA'),
(114, 'Baler', 'PH-AUR'),
(115, 'Casiguran', 'PH-AUR'),
(116, 'Dilasag', 'PH-AUR'),
(117, 'Dinalungan', 'PH-AUR'),
(118, 'Dingalan', 'PH-AUR'),
(119, 'Dipaculao', 'PH-AUR'),
(120, 'Maria Aurora', 'PH-AUR'),
(121, 'San Luis', 'PH-AUR');

